/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Library {
    public boolean someLibraryMethod() {

        var x = 1;
        var y = 2;    

        // todo: remove this    

        return true;
    }
}
